// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package sqlite

import ()

type KnownGuild struct {
	GuildID           int64
	ChannelID         int64
	RoleID            int64
	InitUserID        int64
	RegisteredMessage string
}

type Member struct {
	GuildID  int64
	UserID   int64
	Metadata string
}
