// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type KnownGuild struct {
	GuildID           int64
	ChannelID         int64
	RoleID            int64
	InitUserID        int64
	RegisteredMessage string
	AdminRoleID       pgtype.Int8
}

type Member struct {
	GuildID  int64
	UserID   int64
	Email    string
	Metadata []byte
}

type Meta struct {
	V int16
}

type PinCode struct {
	GuildID int64
	UserID  int64
	Pin     int16
}

type RegistrationSubmission struct {
	GuildID  int64
	UserID   int64
	Metadata []byte
	ExpireAt pgtype.Timestamp
}
