// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package postgres

import (
	"time"

	"github.com/jackc/pgtype"
)

type KnownGuild struct {
	GuildID           int64
	ChannelID         int64
	RoleID            int64
	InitUserID        int64
	RegisteredMessage string
}

type Member struct {
	GuildID  int64
	UserID   int64
	Email    string
	Metadata pgtype.JSONB
}

type Meta struct {
	V int16
}

type PinCode struct {
	GuildID int64
	UserID  int64
	Pin     int16
}

type RegistrationSubmission struct {
	GuildID  int64
	UserID   int64
	Metadata pgtype.JSONB
	ExpireAt time.Time
}
